require "../../require_gemfile"

require_gemfile "../../sources.gemfile"

# Specify your gem's dependencies in test_utils.gemspec
gemspec

gem 'shoulda', git: 'https://github.com/thoughtbot/shoulda', branch: 'ew-update-shoulda-matchers-in-readme'
