# Project local gems
path ".."
path "../../gems"

# source 'https://myprivategemserver.net'
source "https://rubygems.org"

gemspec

gem 'test_utils'
gem 'shoulda', git: 'https://github.com/thoughtbot/shoulda', branch: 'ew-update-shoulda-matchers-in-readme'
